In [1]:
import numpy as np

In [4]:
np.random.random()

0.7486500999734708

In [16]:
np.random.seed(1)
np.random.random()

0.417022004702574

In [24]:
np.random.uniform(3,10)

5.77737231961469

In [31]:
np.random.uniform(1,100,10).reshape(2,5)

array([[59.06894901, 90.43678961, 14.60999571, 14.78835838, 80.93173758],
       [40.37000686, 17.37006551, 92.82334946, 35.42882011, 75.33039821]])

In [35]:
np.random.randint(1,10,15).reshape(3,5)

array([[9, 3, 4, 2, 3],
       [8, 3, 7, 1, 3],
       [7, 7, 3, 8, 8]], dtype=int32)

In [37]:
a=np.random.randint(1,10,6)
a

array([1, 7, 6, 2, 3, 2], dtype=int32)

In [41]:
np.max(a)


np.int32(7)

In [42]:
a[np.argmax(a)]

np.int32(7)

In [45]:
a[np.argmin(a)]

np.int32(1)