In [2]:
import numpy as np


In [3]:

arr1 = np.array([1,2,3,4,5,6])
arr1

array([1, 2, 3, 4, 5, 6])

In [4]:
type(arr1)

numpy.ndarray

In [6]:
arr2= np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
arr4=np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
arr5=np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
arr6=np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr7=np.linspace(10,2,10)
arr7

array([10.        ,  9.11111111,  8.22222222,  7.33333333,  6.44444444,
        5.55555556,  4.66666667,  3.77777778,  2.88888889,  2.        ])

In [17]:
arr8=arr7.copy()
arr8

array([10.        ,  9.11111111,  8.22222222,  7.33333333,  6.44444444,
        5.55555556,  4.66666667,  3.77777778,  2.88888889,  2.        ])

In [19]:
arr1.shape

(6,)

In [21]:
arr2.shape

(2, 3)

In [23]:
arr3.shape

(2, 3)

In [25]:
arr5.shape

(5, 5)

In [31]:
arr9=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [32]:
arr9.shape

(2, 2, 2)

In [33]:
arr9.ndim

3

In [34]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
arr2.ndim

2

In [36]:
arr1.ndim

1

In [37]:
arr1.size

6

In [38]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
arr2.size


6

In [40]:
arr2.itemsize

8

In [41]:
arr1.dtype

dtype('int64')

In [43]:
arr9.astype('float')

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [45]:
lista =range(100)
arr11=np.arange(100)

In [46]:
import sys

In [47]:
print(sys.getsizeof(87)*len(lista))

2800


In [48]:
print(arr11.itemsize*arr11.size)

800


In [49]:
import time

In [53]:
x=range(100000)
y=range(100000,200000)
start_time =time.time()

c=[ (x,y) for x,y in zip(x,y) ]
print(time.time()-start_time)

0.029599905014038086


In [57]:
a=np.arange(100000)
b= np.arange(100000,200000)
start_time =time.time()
c=a+b
print(time.time()-start_time)

0.0015211105346679688


In [60]:
arr12=np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [63]:
arr1[2:4]

array([3, 4])

In [66]:
arr12[:,1:4]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19],
       [21, 22, 23]])

In [67]:
for i in arr12:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [68]:
for i in np.nditer(arr12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [71]:
arr1
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
arr2.ravel()

array([1, 2, 3, 4, 5, 6])

In [78]:
arr4.transpose()

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])